# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.3
loader_version=0.18.4
kotlin_loader_version=1.13.9+kotlin.2.3.10
# Mod Properties
mod_version=v1.0.1+26.3.0
maven_group=com.h3liiix
archives_base_name=BetterVanillaDragonFight
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.161.0+26.3
